############################################################
#
# article微服务
# web访问端口号  约定：8001
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev   # yml中配置文件的环境配置，dev：开发环境，test：测试环境，prod：生产环境
  application:
    name: service-article
  cloud:
    nacos:
      discovery:
        service: service-article
      server-addr: 192.168.31.101:8848
    sentinel:
      transport:
        dashboard: 192.168.31.101:8080 # 控制台地址
        prot: 8719
    stream:
      bindings:                           # 绑定通道和交换机
        myOutput:                         # 定义生产者的通道
          # 自定义交换机的名字，也就是代码里构建的消息，交给底层mq的交换机
          destination: streamExchange
        myInput:                          # 定义消费者的通道
          # 自定义交换机的名字，也就是消息从底层mq输入到消费端进行消费
          destination: streamExchange
          group: boys
  datasource:                                         # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://localhost:3306/zyx_news_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://root:root@192.168.31.101:27017
      database: zyx_news
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/
  rabbitmq:
    host: 192.168.31.101
    port: 5672
    username: admin
    password: admin
    virtual-host: zyx-news-service
#  zipkin:
#    # 配置zipkin采集的服务地址，数据会发送到这里
#    base-url: http://192.168.1.2:9411/
#    sender:
#      # 数据采集的传输通信方式，web http的形式
#      type: web
#  sleuth:
#    sampler:
#      # 数据采样比例（百分数），0~1
#      probability: 1

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.zyx.pojo          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件

############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.zyx.my.mapper.MyMapper
  not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true


# 定义freemarker生成的html位置
freemarker:
  html:
    target: /workspace/freemarker_html
    article: /Users/leechenxiang/Desktop/apache-tomcat-9.0.22/webapps/imooc-news/portal/a

# 配置指定自定义的ribbon规则
#SERVICE-USER:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  ConnectTimeout: 5000          # 创建连接的超时时间，单位：ms
  ReadTimeout: 5000             # 在连接创建好以后，调用接口的超时时间，单位：ms
  MaxAutoRetries: 1             # 最大重试次数
  MaxAutoRetriesNextServer: 2   # 切换到下个微服务实例的重试次数
  # 当请求到某个微服务5s，超时后会进行重试，先重试连接自己当前的这个实例
  # 如果当前重试失败1次，则会切换到访问集群中的下一个微服务实例，切换最大为2次

# 开启日志的配置
logging:
  level:
    com.zyx.api.controller.user.UserControllerApi: debug
#    root: debug

# 配置feign
feign:
  client:
    config:
      # 配置服务提供方的名称
      service-user:
        loggerLevel: FULL
  hystrix:
    enabled: true   # 打开feign客户端的内置hystrix
