############################################################
#
# 网管服务gateway
# web访问端口号  约定：8700
#
############################################################
server:
  port: 8700
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: springcloud-gateway
  cloud:
    nacos:
      discovery:
        service: gateway
      server-addr: 192.168.31.101:8848
    gateway:
      discovery:
        locator:
          enabled: true # 开启动态路由，从注册中心根据微服务名称获取目标节点
      routes:
        - id: userRoute # 路由id可以自定义，保证全局唯一
          uri: lb://service-user # lb 代表负载均衡，会动态寻址
#          uri: http://192.168.31.1:8001 # 后端服务节点的路由url地址
          predicates:                   # 匹配断言，符合条件则匹配
            - Path=/user/**
#          filters:
#            - StripPrefix=1
#    config:
#      server:
#        git:
#          uri: https://github.com/zyx-team/zyx-news-config.git
  rabbitmq:
    host: 192.168.31.101
    port: 5672
    username: admin
    password: admin
    virtual-host: zyx-news-service


# 配置动态刷新git配置的路径终端请求地址
management:
  endpoints:
    web:
      exposure:
        include: "*"
